#!/usr/bin/env python3
"""Run several commands on a number of hosts

sshit reads the commands to run from stdin.

Usage:
    sshit [HOSTS ...]

"""
import sys
import docopt
import sh
import trio



async def execute_remotely(q, command):
    host = await q.get()
    await trio.run_sync_in_worker_thread(sh.ssh, host, command)
    await q.put(host)


async def main(hosts):
    q = trio.Queue(len(hosts))
    for host in hosts:
        await q.put(host)
    async with trio.wrap_file(sys.stdin) as f:
        async with trio.open_nursery() as nursery:
            async for line in f:
                nursery.start_soon(execute_remotely, q, line)


if __name__ == "__main__":
    ARGS = docopt.docopt(__doc__, version="0.0.1")
    trio.run(main, ARGS["HOSTS"])
