#!/usr/bin/env python3
"""Run several commands on a number of hosts

Usage:
    sshit [HOSTS ...]

"""
import sys
import queue
import threading
import docopt
from sh import ssh


def worker(myhost):
    """Run all commands of a host."""
    while True:
        command = q.get()
        if command is None:
            break
        ssh(myhost, command)
        q.task_done()


if __name__ == '__main__':
    ARGS = docopt.docopt(__doc__, version="0.0.1")
    hosts = ARGS["HOSTS"]
    q = queue.Queue()
    threads = []
    for host in hosts:
        t = threading.Thread(target=worker, args=(host,))
        t.start()
        threads.append(t)
    for item in sys.stdin:
        q.put(item)
    q.join()
    for _ in hosts:
        q.put(None)
    for t in threads:
        t.join()
